### PR TITLE
Added a new mod

### PR DESCRIPTION
**Pull request by bnfour**
Hi! I've just released a brand new mod in my repo and would like to add it here as well.

I'm opening a pull as a way to highlight that it's a new thing (and also I'll appreciate better wording for the description, as usual).

The mod is a bunch of UI fixed bundled together, you can read what it does at https://github.com/bnfour/md-mods#ui-tweaks

### CODE REVIEW

**Comment by lxymahatma** [comment]
> Hi! I've just released a brand new mod in my repo and would like to add it here as well.
> 
> I'm opening a pull as a way to highlight that it's a new thing (and also I'll appreciate better wording for the description, as usual).
> 
> The mod is a bunch of UI fixed bundled together, you can read what it does at https://github.com/bnfour/md-mods#ui-tweaks

for description stuff just ask gpt ig, this is what i got from gpt: "Providing customizable options for various UI elements"

**Comment by bnfour** [comment]
Yeah, that could be an option. I guess my original one is close enough.

I just realized I forgot to update the readme table, will push an update soon.

**Comment by lxymahatma** [comment]
> Yeah, that could be an option. I guess my original one is close enough.
> 
> I just realized I forgot to update the readme table, will push an update soon.

~readme table havent been updated for a long time actually so doesnt really matter~
cz im really busy with my school stuff ~and play other games~ basically no time to maintain md mods related things. MDMT rewrite is still... on going without ui, i just rewrite the whole backend and ui design is still painful lol

**Comment by bnfour** [comment]
I completely understand the business part.
But still, I'd like to keep things tidy, at least by not introducing more confusion in the repos I push to, so I've updated the readme as well.

Let me know if something else is needed.

**Comment by lxymahatma** [comment]
> I completely understand the business part. But still, I'd like to keep things tidy, at least by not introducing more confusion in the repos I push to, so I've updated the readme as well.
> 
> Let me know if something else is needed.

👍i think it's fine now

**Pull request merged**
