### PR TITLE
updated bnfour/AlbumScroll and bnfour/TrueAbove1kRank to 2.0.0 (v8)

### PR DESCRIPTION
**Pull request by bnfour**
Sorry, I forgot to update my mods here after I released new versions for the updated MelonLoader.

This pull includes new versions for the AlbumScroll and TrueAbove1kRank mods, the only change is net6.0 runtime for MelonLoader 0.6.1.

The ScoreboardCharacters mod now has external dependencies (SkiaSharp DLLs to go to the UserLibs folder). I see that there is a `DependentLibs` property in the json file, but I'm not sure how to include the libs properly. I'll appreciate your help on this.

### CODE REVIEW

**Comment by lxymahatma** [comment]
Ideally the DependentLibs should have the same format as the mod DownloadLink thing "Libs/xxx.dll"
but I'm not sure whether I correctly included download dependentlibs bc ~~we dont have any dependentlibs before so i might only write code to deal with mod dependency stuff~~
also i heard ashton is gonna rewrite scoreboardcharacters mod and make a pr👀

**Comment by lxymahatma** [comment]
btw mdmt now is in low maintenance period cz i want to rewrite the whole ui ~~but no one can design it for me and i know nothing about ui design so kinda embarrassing~~
 i don't want to add more functions on the old mdmt ~~but cant finish the new one 😣~~

**Comment by bnfour** [comment]
No problem, totally understand your position about the older version.

For now, the mod is still available to download via my repo with its dependencies, so it's not like the end of the world (though, apparently, it might be confusing for the users).

**Comment by lxymahatma** [comment]
> No problem, totally understand your position about the older version.
> 
> For now, the mod is still available to download via my repo with its dependencies, so it's not like the end of the world (though, apparently, it might be confusing for the users).

yeah hope someone can write ui for me ~~or give me a design proposal~~ cz it's toooooooo hard for me to think about arranging the buttons and stuff 😭

**Pull request merged**
